# Generated by Django 5.2.10 on 2026-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
